name: Flutter Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
jobs:
  flutter-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Run tests
        run: |
          flutter test

      - name: Install Newman
        run: npm install -g newman
      
      - name: Run API Tests
        run: newman run test/flutter.postman_collection.json
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install selenium
        run: |
          pip install selenium      

      - name: Run Selenium tests
        run: |
          python test.py
